# # Specify the version for docker-compose.yml
# version: "3.9"
# # add the serivces needed (postgres,go)-
# services:
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DB: simple_bank
#     ports:
#       - 5432:5432
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
    
#   api:
#     build:
#       context: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres


# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)
      # POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 10s
      timeout: 5s
      retries: 5

  go:
    container_name: go
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy # waiting until heathcheck of postgres is good
    ports:
      - "3000:3000"

volumes:
  dbdata:
